### PR TITLE
add babel-plugin-external-helpers

### PR DESCRIPTION
**Pull request by Remexllee**
I try this project on my local, I find out it missing "babel-plugin-external-helpers" in package.json, after install it the demo running good in my concept2 rowing machine.

### CODE REVIEW

**Comment by Remexllee** [comment]
I signed it!

**Comment by Remexllee** [comment]
I signed it!

**Comment by Remexllee** [comment]
I signed it!

**Comment by andreban** [comment]
Looks like the e-mail used on the commit doesn't match the e-mail on the Github account that signed the CLA, so the validation is failing. 

screen shot 2017-04-20 at 9 41 12 am

You can click on your profile logo, then Settings, and then e-mail and add an extra e-mail. I think Github asks for e-mail validation, so it must be a valid e-mail. Another option is to re-submit the PR with the commit using the email that signed the CLA.

**Comment by Remexllee** [comment]
Got it, I had change my local github email. I will close this PR and create a new one.
Thanks for your information.

**Pull request closed without merging**
